OBJECTS=ttatd_genh.o util.o
EXE_NAME=ttatd_genh$(EXE_EXT)

all: $(EXE_NAME)

$(EXE_NAME): ttatd_genh.o util.o

ttatd_genh.o: ttatd_genh.c error_stuff.h util.h

util.o: util.c error_stuff.h util.h

clean:
	rm -f $(EXE_NAME) $(OBJECTS)
