OBJECTS=revb.o util.o
EXE_NAME=revb$(EXE_EXT)

all: $(EXE_NAME)

$(EXE_NAME): revb.o util.o

revb.o: revb.c error_stuff.h util.h

util.o: util.c error_stuff.h util.h

clean:
	rm -f $(EXE_NAME) $(OBJECTS)
