OBJECTS=bincut.o util.o
EXE_NAME=bincut$(EXE_EXT)

all: $(EXE_NAME)

$(EXE_NAME): bincut.o util.o

bincut.o: bincut.c error_stuff.h util.h

util.o: util.c error_stuff.h util.h

clean:
	rm -f $(EXE_NAME) $(OBJECTS)
